// ============================================
// CONFIGURATION — API Keys & Destination Data
// ============================================

const CONFIG = {
    // API key is loaded from secrets.js (gitignored)
    GOOGLE_API_KEY: '',
    BASEMAPS_API_KEY: '',

    // Supported destinations with coordinates and metadata
    DESTINATIONS: {
        'tirupati': {
            name: 'Tirupati',
            lat: 13.6288,
            lng: 79.4192,
            state: 'Andhra Pradesh',
            tagline: 'Sacred Seven Hills and Sri Venkateswara Swamy Temple',
            subtitle: 'Tirumala Sacred Hills & Shrines',
            coordsText: '13.6288° N, 79.4192° E • Sacred Seven Hills & Temples',
            photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Tirumala_Venkateswara_Temple.jpg/800px-Tirumala_Venkateswara_Temple.jpg',
            pacingScore: 96,
            crowdLevel: 'Moderate',
            transitText: 'APSRTC Ghat Road EV Shuttle',
            weatherText: '29°C • Pleasant Hills',
            tags: ['religious', 'culture', 'history', 'family', 'pilgrimage'],
            bestMonths: [9, 10, 11, 12, 1, 2, 3],
            avgDailyBudget: { budget: 1500, standard: 3500, premium: 7000 }
        },
        'goa': {
            name: 'Goa',
            lat: 15.2993,
            lng: 74.124,
            state: 'Goa',
            tagline: 'Beaches, nightlife, and Portuguese charm',
            subtitle: 'Cola Bay & Betul Estuary',
            coordsText: '15.0543° N, 73.9789° E • Hillside & Coastal Bay',
            photo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCUGZbubUW9qbJ8ZrLwZeOr55j-eT7-5lVXC5jQ9gGIJLYw6SvSdGAa4BR2AbzsGcTMIBjfCOENXSrOAM-CSyuf0ovKuRH_zpSunU9hTxOZaWtnkA6KZ6CkEso_CXqXXRChtB-CnM8wdvxpMNKswT6m_WglLlaxaj8dJeGMFFk34pM6DCzdHnRgLWf1ooab-wFj0641673Z1SEWTzOeEmlGADzaUuzHYusX1udnOVy7qFRtK6V11ngc',
            pacingScore: 94,
            crowdLevel: 'Low',
            transitText: 'Scenic Coastal Highway Route',
            weatherText: '28°C • Pleasant Breeze',
            tags: ['beach', 'nightlife', 'food', 'adventure', 'relaxation'],
            bestMonths: [11, 12, 1, 2, 3],
            avgDailyBudget: { budget: 2500, standard: 5000, premium: 10000 }
        },
        'munnar': {
            name: 'Munnar',
            lat: 10.0889,
            lng: 77.0595,
            state: 'Kerala',
            tagline: 'Tea gardens, misty hills, and cool weather',
            subtitle: 'Mist & Spice Corridors',
            coordsText: '10.0889° N, 77.0595° E • Tea Terraces & Hill Country',
            photo: 'https://lh3.googleusercontent.com/aida/AEtjO1UestpEKJCyjWN0SBBscpOaQqk6TMOaOyWYqRUSGSKL2c7bRiC0HzElbdIrKeQc9j25-I20lchMP8g19OgLwOSID-8fHHaMm5TN9h6hwqYSEVZeGhEhEf0VXh52paH9fYdK021UAfMhnNOcw0vSFMk4CC7UYoBWYyL9uqxwJe4mrZ78O6ZlPHdFpURz410d4lO-qkeKC3K8tVkFy1EUpc2fCQw139o46wFdIRtVf91iPnl_6bSaQ7_B-zo',
            pacingScore: 96,
            crowdLevel: 'Very Low',
            transitText: 'Mountain Gap Scenic Route',
            weatherText: '20°C • Cool Mist',
            tags: ['nature', 'relaxation', 'adventure', 'culture'],
            bestMonths: [9, 10, 11, 12, 1, 2, 3],
            avgDailyBudget: { budget: 1800, standard: 4000, premium: 8000 }
        },
        'pondicherry': {
            name: 'Pondicherry',
            lat: 11.9416,
            lng: 79.8083,
            state: 'Puducherry',
            tagline: 'French Quarter, cafés, and serene beaches',
            subtitle: 'White Town & Promenades',
            coordsText: '11.9416° N, 79.8083° E • French Heritage & Coastal Streets',
            photo: 'https://lh3.googleusercontent.com/aida/AEtjO1UIda6VngiEQiPzPyO12pC9gBPkwnl_IdmVJR3xyvqwlPC2qSKgVfS0bdlOVmAlOM8AFAAq3E2ELvQIicW83r0UppfCFm7HxEXqSvlAw3V1PjKx87n26I7iypeXIri7dNDK4azCh-Z64IkUO4PiwtOEXELZmxI3GcYgE3RV2RhdRy7LUd2yELFp2vsRX_frfknRqa1VQxPqAjI43796HOBsueVPywf8uj56nRaaMpBBXEmtoTSPXuoEGNA',
            pacingScore: 92,
            crowdLevel: 'Low',
            transitText: 'East Coast Scenic Highway',
            weatherText: '29°C • Sunny Breeze',
            tags: ['culture', 'food', 'beach', 'relaxation', 'history'],
            bestMonths: [10, 11, 12, 1, 2, 3],
            avgDailyBudget: { budget: 2000, standard: 4000, premium: 8000 }
        },
        'varanasi': {
            name: 'Varanasi',
            lat: 25.3176,
            lng: 82.9739,
            state: 'Uttar Pradesh',
            tagline: 'Kashi Vishwanath, ancient ghats, and evening Ganga Aarti',
            subtitle: 'Ganga Ghats & Kashi Corridor',
            coordsText: '25.3176° N, 82.9739° E • Ancient Ghats & Spiritual Heart',
            photo: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?q=80&w=1200&auto=format&fit=crop',
            pacingScore: 91,
            crowdLevel: 'High',
            transitText: 'Ghat Heritage Walk & Electric Ferry',
            weatherText: '26°C • Clear Evening',
            tags: ['religious', 'culture', 'history', 'food', 'pilgrimage'],
            bestMonths: [10, 11, 12, 1, 2, 3],
            avgDailyBudget: { budget: 1500, standard: 3500, premium: 7000 }
        },
        'hampi': {
            name: 'Hampi',
            lat: 15.335,
            lng: 76.46,
            state: 'Karnataka',
            tagline: 'Ancient ruins and boulder-strewn landscapes',
            subtitle: 'Vijayanagara Historic Sites',
            coordsText: '15.3350° N, 76.4600° E • Boulder Landscapes & Ancient Temples',
            photo: 'https://lh3.googleusercontent.com/aida/AEtjO1XZ9hyXbDJwU5lKW4v5wrZ0WYJKFCDft3w8UoUZiJCdm0tIKLXseIuhKGff1QjHjZfpeJPXIvGVM5khDC_1rWWq0rZlkm1hJwdpugJt4ZIqwGG0kA3sNJyR9awpdfbw556mC3qfzkxVIrH45kkMlKqQxwiyQ0thXzLU28d3ZwAyPV01wQMmcSqFjkxbYd3p6Ii8NOnac70NG2PLNqi5Ufq6XYBOIZKP0vW6RMCzFKYkumEMC7KSsTUDHOo',
            pacingScore: 90,
            crowdLevel: 'Moderate',
            transitText: 'Heritage Highway Route',
            weatherText: '31°C • Clear Sky',
            tags: ['history', 'culture', 'adventure', 'budget'],
            bestMonths: [10, 11, 12, 1, 2],
            avgDailyBudget: { budget: 1200, standard: 2500, premium: 5000 }
        },
        'kochi': {
            name: 'Kochi',
            lat: 9.9312,
            lng: 76.2673,
            state: 'Kerala',
            tagline: 'Backwaters, spices, and coastal culture',
            subtitle: 'Coastal Forts & Canals',
            coordsText: '9.9312° N, 76.2673° E • Coastal Lagoons & Heritage Town',
            photo: 'https://lh3.googleusercontent.com/aida/AEtjO1XfG2nXpYpDuEBLqo9A6ELDD-lLwzNZ6g2GFMzkig7gp7n_b7Z5YUHHA4d3uDGPqYoNCnSReV6NULas4lQUyi_nZQc6zAezf9P9ymJLbjclRdZu2UNC_Xwpzc94_uf6iKzYu53_CeUfnQ4l0Oliztcdqk0i9OktsVeftgW7BE-QEEUFQQstoN-16EXzHJjoDwxUME38aNZ7mdrFhvGv2LQiO2hyc8AhgyPXnEoxbxXcPncMlwwmOeJvBYg',
            pacingScore: 93,
            crowdLevel: 'Low',
            transitText: 'Island Ferry & Coastal Bridge',
            weatherText: '27°C • Coastal Breeze',
            tags: ['culture', 'nature', 'food', 'history', 'relaxation'],
            bestMonths: [10, 11, 12, 1, 2],
            avgDailyBudget: { budget: 2000, standard: 4500, premium: 9000 }
        },
        'mysore': {
            name: 'Mysore',
            lat: 12.2958,
            lng: 76.6394,
            state: 'Karnataka',
            tagline: 'Royal palaces, silk, and sandalwood',
            subtitle: 'Royal Palaces & Silk Corridors',
            coordsText: '12.2958° N, 76.6394° E • Royal Heritage & Distilleries',
            photo: 'https://lh3.googleusercontent.com/aida/AEtjO1XfG2nXpYpDuEBLqo9A6ELDD-lLwzNZ6g2GFMzkig7gp7n_b7Z5YUHHA4d3uDGPqYoNCnSReV6NULas4lQUyi_nZQc6zAezf9P9ymJLbjclRdZu2UNC_Xwpzc94_uf6iKzYu53_CeUfnQ4l0Oliztcdqk0i9OktsVeftgW7BE-QEEUFQQstoN-16EXzHJjoDwxUME38aNZ7mdrFhvGv2LQiO2hyc8AhgyPXnEoxbxXcPncMlwwmOeJvBYg',
            pacingScore: 94,
            crowdLevel: 'Moderate',
            transitText: 'Expressway & Palace Corridor',
            weatherText: '26°C • Pleasant',
            tags: ['culture', 'history', 'food', 'shopping'],
            bestMonths: [10, 11, 12, 1, 2],
            avgDailyBudget: { budget: 1500, standard: 3500, premium: 7000 }
        },
        'puri': {
            name: 'Puri',
            lat: 19.8135,
            lng: 85.8312,
            state: 'Odisha',
            tagline: 'Shree Jagannath Dham and serene golden beach',
            subtitle: 'Jagannath Dham & Golden Beach',
            coordsText: '19.8135° N, 85.8312° E • Coastal Shrines & Sacred Beach',
            photo: 'https://images.unsplash.com/photo-1628155930542-3c7a64e2c833?q=80&w=1200&auto=format&fit=crop',
            pacingScore: 93,
            crowdLevel: 'Moderate',
            transitText: 'Grand Road Shuttle & Coastal Drive',
            weatherText: '28°C • Coastal Breeze',
            tags: ['religious', 'beach', 'culture', 'history', 'pilgrimage'],
            bestMonths: [10, 11, 12, 1, 2],
            avgDailyBudget: { budget: 1500, standard: 3500, premium: 7000 }
        },
        'amritsar': {
            name: 'Amritsar',
            lat: 31.6340,
            lng: 74.8723,
            state: 'Punjab',
            tagline: 'Harmandir Sahib Golden Temple and Punjabi cuisine',
            subtitle: 'Golden Temple & Heritage Walk',
            coordsText: '31.6340° N, 74.8723° E • Sacred Sarovar & Heritage Walk',
            photo: 'https://images.unsplash.com/photo-1514222134-b57cbb8ce073?q=80&w=1200&auto=format&fit=crop',
            pacingScore: 95,
            crowdLevel: 'Moderate',
            transitText: 'Heritage Walkways & Metro Bus',
            weatherText: '24°C • Pleasant Evening',
            tags: ['religious', 'culture', 'food', 'history', 'pilgrimage'],
            bestMonths: [10, 11, 12, 1, 2, 3],
            avgDailyBudget: { budget: 1800, standard: 3800, premium: 7500 }
        },
        'rishikesh': {
            name: 'Rishikesh',
            lat: 30.0869,
            lng: 78.2676,
            state: 'Uttarakhand',
            tagline: 'Yoga capital, emerald Ganga, and Himalayan foothills',
            subtitle: 'Ganga Foothills & Laxman Jhula',
            coordsText: '30.0869° N, 78.2676° E • Himalayan Valleys & Sacred River',
            photo: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=80&w=1200&auto=format&fit=crop',
            pacingScore: 94,
            crowdLevel: 'Low',
            transitText: 'Scenic Valley Route & Cable Car',
            weatherText: '22°C • Crisp Mountain Air',
            tags: ['adventure', 'religious', 'nature', 'wellness'],
            bestMonths: [9, 10, 11, 2, 3, 4],
            avgDailyBudget: { budget: 1600, standard: 3600, premium: 8000 }
        },
        'alleppey': {
            name: 'Alleppey',
            lat: 9.4981,
            lng: 76.3388,
            state: 'Kerala',
            tagline: 'Houseboats, backwaters, and village life',
            subtitle: 'Vembanad Lake & Canals',
            coordsText: '9.4981° N, 76.3388° E • Backwater Canals & Lagoons',
            photo: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=1200&auto=format&fit=crop',
            pacingScore: 95,
            crowdLevel: 'Low',
            transitText: 'Waterway Cruise & Solar Ferry',
            weatherText: '27°C • Warm & Serene',
            tags: ['nature', 'relaxation', 'culture', 'food'],
            bestMonths: [9, 10, 11, 12, 1, 2, 3],
            avgDailyBudget: { budget: 2200, standard: 5000, premium: 12000 }
        },
        'bangalore': {
            name: 'Bangalore',
            lat: 12.9716,
            lng: 77.5946,
            state: 'Karnataka',
            tagline: 'Garden city with microbreweries, parks, and culture',
            subtitle: 'Lalbagh & Tech Corridors',
            coordsText: '12.9716° N, 77.5946° E • Garden City & Urban Groves',
            photo: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?q=80&w=1200&auto=format&fit=crop',
            pacingScore: 91,
            crowdLevel: 'Moderate',
            transitText: 'Namma Metro & Outer Ring Route',
            weatherText: '25°C • Pleasant',
            tags: ['food', 'nightlife', 'shopping', 'culture'],
            bestMonths: [10, 11, 12, 1, 2, 3],
            avgDailyBudget: { budget: 2000, standard: 4500, premium: 9000 }
        },
        'coorg': {
            name: 'Coorg',
            lat: 12.4244,
            lng: 75.7382,
            state: 'Karnataka',
            tagline: 'Coffee estates and misty Western Ghats',
            subtitle: 'Madikeri & Coffee Valleys',
            coordsText: '12.4244° N, 75.7382° E • Coffee Terraces & Rainforest',
            photo: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?q=80&w=1200&auto=format&fit=crop',
            pacingScore: 95,
            crowdLevel: 'Very Low',
            transitText: 'Ghat Road Estate Transit',
            weatherText: '21°C • Cool Mist',
            tags: ['nature', 'relaxation', 'adventure', 'food'],
            bestMonths: [10, 11, 12, 1, 2, 3],
            avgDailyBudget: { budget: 1800, standard: 4000, premium: 8000 }
        },
        'jaipur': {
            name: 'Jaipur',
            lat: 26.9124,
            lng: 75.7873,
            state: 'Rajasthan',
            tagline: 'Pink City palaces, Amber Fort, and royal heritage',
            subtitle: 'Amber Fort & Hawa Mahal',
            coordsText: '26.9124° N, 75.7873° E • Royal Heritage & Hilltop Forts',
            photo: 'https://images.unsplash.com/photo-1603288967393-27d97607730e?q=80&w=1200&auto=format&fit=crop',
            pacingScore: 92,
            crowdLevel: 'Moderate',
            transitText: 'Heritage Boulevard Route',
            weatherText: '27°C • Sunny',
            tags: ['culture', 'history', 'food', 'shopping'],
            bestMonths: [10, 11, 12, 1, 2, 3],
            avgDailyBudget: { budget: 2000, standard: 4500, premium: 9500 }
        },
        'ooty': {
            name: 'Ooty',
            lat: 11.4102,
            lng: 76.6950,
            state: 'Tamil Nadu',
            tagline: 'Queen of Hill Stations, botanical gardens, and toy train',
            subtitle: 'Nilgiri Hills & Botanical Gardens',
            coordsText: '11.4102° N, 76.6950° E • Mountain Tea Gardens',
            photo: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?q=80&w=1200&auto=format&fit=crop',
            pacingScore: 95,
            crowdLevel: 'Low',
            transitText: 'Nilgiri Heritage Mountain Rail',
            weatherText: '17°C • Crisp & Refreshing',
            tags: ['nature', 'relaxation', 'adventure', 'family'],
            bestMonths: [9, 10, 11, 12, 1, 2, 3, 4],
            avgDailyBudget: { budget: 1800, standard: 4200, premium: 8500 }
        }
    },

    // Budget estimation ratios (% of total budget)
    // Intentionally totals ~88% to leave a healthy buffer
    BUDGET_SPLIT: {
        accommodation: 0.28,
        transport: 0.18,
        food: 0.22,
        activities: 0.12,
        misc: 0.08
    },

    // Default itinerary time slots
    DAY_TEMPLATE: [
        { time: '08:00', label: 'Morning', type: 'activity' },
        { time: '10:30', label: 'Mid-morning', type: 'activity' },
        { time: '13:00', label: 'Lunch', type: 'food' },
        { time: '15:00', label: 'Afternoon', type: 'activity' },
        { time: '17:30', label: 'Evening', type: 'activity' },
        { time: '20:00', label: 'Dinner', type: 'food' }
    ]
};
